apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-config
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: psltest

# Connect to DB :
# kubectl exec -it pg-deployment-7459f8b5bf-6dvm9 -n k8s-project --  psql -h localhost -U admin --password -p 5432 postgresdb